---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keptn-default
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/part-of: keptn-{{ .Release.Namespace }}
    app.kubernetes.io/component: {{ include "control-plane.name" . }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keptn-configuration-service
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/part-of: keptn-{{ .Release.Namespace }}
    app.kubernetes.io/component: {{ include "control-plane.name" . }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keptn-shipyard-controller
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/part-of: keptn-{{ .Release.Namespace }}
    app.kubernetes.io/component: {{ include "control-plane.name" . }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keptn-secret-service
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/part-of: keptn-{{ .Release.Namespace }}
    app.kubernetes.io/component: {{ include "control-plane.name" . }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keptn-lighthouse-service
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/part-of: keptn-{{ .Release.Namespace }}
    app.kubernetes.io/component: {{ include "control-plane.name" . }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keptn-api-service
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/part-of: keptn-{{ .Release.Namespace }}
    app.kubernetes.io/component: {{ include "control-plane.name" . }}
---
{{- if .Values.webhookService.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keptn-webhook-service
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/part-of: keptn-{{ .Release.Namespace }}
    app.kubernetes.io/component: {{ include "control-plane.name" . }}
---
{{- end }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keptn-manage-secrets
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/part-of: keptn-{{ .Release.Namespace }}
    app.kubernetes.io/component: {{ include "control-plane.name" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - get
      - delete
      - update
      - list

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keptn-get-secrets
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/part-of: keptn-{{ .Release.Namespace }}
    app.kubernetes.io/component: {{ include "control-plane.name" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keptn-manage-roles
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/part-of: keptn-{{ .Release.Namespace }}
    app.kubernetes.io/component: {{ include "control-plane.name" . }}
rules:
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - roles
    verbs:
      - create
      - get
      - delete
      - update
      - deletecollection
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keptn-manage-rolebindings
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/part-of: keptn-{{ .Release.Namespace }}
    app.kubernetes.io/component: {{ include "control-plane.name" . }}
rules:
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - rolebindings
    verbs:
      - create
      - get
      - delete
      - update
      - deletecollection
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keptn-read-metadata
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/part-of: keptn-{{ .Release.Namespace }}
    app.kubernetes.io/component: {{ include "control-plane.name" . }}
rules:
  - apiGroups:
      - extensions
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keptn-manage-configmaps
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/part-of: keptn-{{ .Release.Namespace }}
    app.kubernetes.io/component: {{ include "control-plane.name" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
      - update
      - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keptn-delete-bridge-pod
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/part-of: keptn-{{ .Release.Namespace }}
    app.kubernetes.io/component: {{ include "control-plane.name" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - delete
      - deletecollection

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keptn-acquire-lease
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/part-of: keptn-{{ .Release.Namespace }}
    app.kubernetes.io/component: {{ include "control-plane.name" . }}
rules:
  - apiGroups:
      - "coordination.k8s.io"
    resources:
      - leases
    resourceNames:
      - "shipyard-controller-dispatcher"
    verbs:
      - get
      - update
      - create


---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keptn-lighthouse-service
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/part-of: keptn-{{ .Release.Namespace }}
    app.kubernetes.io/component: {{ include "control-plane.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: keptn-manage-configmaps
subjects:
  - kind: ServiceAccount
    name: keptn-lighthouse-service

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keptn-api-service-metadata
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/part-of: keptn-{{ .Release.Namespace }}
    app.kubernetes.io/component: {{ include "control-plane.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: keptn-read-metadata
subjects:
  - kind: ServiceAccount
    name: keptn-api-service

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keptn-configuration-service-get-secrets
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/part-of: keptn-{{ .Release.Namespace }}
    app.kubernetes.io/component: {{ include "control-plane.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: keptn-get-secrets
subjects:
  - kind: ServiceAccount
    name: keptn-configuration-service

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keptn-shipyard-controller-manage-secrets
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/part-of: keptn-{{ .Release.Namespace }}
    app.kubernetes.io/component: {{ include "control-plane.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: keptn-manage-secrets
subjects:
  - kind: ServiceAccount
    name: keptn-shipyard-controller

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keptn-secret-service-manage-secrets
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/part-of: keptn-{{ .Release.Namespace }}
    app.kubernetes.io/component: {{ include "control-plane.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: keptn-manage-secrets
subjects:
  - kind: ServiceAccount
    name: keptn-secret-service

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keptn-secret-service-manage-roles
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/part-of: keptn-{{ .Release.Namespace }}
    app.kubernetes.io/component: {{ include "control-plane.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: keptn-manage-roles
subjects:
  - kind: ServiceAccount
    name: keptn-secret-service
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keptn-secret-service-manage-rolebindings
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/part-of: keptn-{{ .Release.Namespace }}
    app.kubernetes.io/component: {{ include "control-plane.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: keptn-manage-rolebindings
subjects:
  - kind: ServiceAccount
    name: keptn-secret-service

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keptn-shipyard-controller-acquire-lease
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/part-of: keptn-{{ .Release.Namespace }}
    app.kubernetes.io/component: {{ include "control-plane.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: keptn-acquire-lease
subjects:
  - kind: ServiceAccount
    name: keptn-shipyard-controller
