---
# remediation-service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: remediation-service
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/part-of: keptn-{{ .Release.Namespace }}
    app.kubernetes.io/component: {{ include "control-plane.name" . }}
spec:
  selector:
    matchLabels: {{- include "common.labels.selectorLabels" . | nindent 6 }}
  replicas: 1
  template:
    metadata:
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/part-of: keptn-{{ .Release.Namespace }}
        app.kubernetes.io/component: {{ include "control-plane.name" . }}
    spec:
      {{- include "control-plane.common.pod-security-context" . | nindent 6 }}
      containers:
      - name: remediation-service
        image: {{ .Values.remediationService.image.repository }}:{{ .Values.remediationService.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "1Gi"
            cpu: "200m"
        env:
          - name: EVENTBROKER
            value: 'http://localhost:8081/event'
          - name: CONFIGURATION_SERVICE
            value: 'http://configuration-service:8080'
          - name: ENVIRONMENT
            value: 'production'
        {{- include "control-plane.common.container-security-context" . | nindent 8 }}
      - name: distributor
        image: {{ .Values.distributor.image.repository }}:{{ .Values.distributor.image.tag | default .Chart.AppVersion }}
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sleep", "30"]
        imagePullPolicy: IfNotPresent
        {{- include "control-plane.dist.livenessProbe" . | nindent 8 }}
        {{- include "control-plane.dist.readinessProbe" . | nindent 8 }}
        ports:
          - containerPort: 8080
        {{- include "keptn.distributor.resources" . | nindent 8 }}
        env:
          - name: PUBSUB_TOPIC
            value: 'sh.keptn.event.get-action.triggered'
          - name: PUBSUB_RECIPIENT
            value: '127.0.0.1'
        {{- include "control-plane.dist.common.env.vars" . | nindent 10 }}
        {{- include "control-plane.common.container-security-context" . | nindent 8 }}
      serviceAccountName: keptn-default
      terminationGracePeriodSeconds: {{ .Values.gracePeriod | default 30 }}
      {{- include "keptn.nodeSelector" (dict "value" .Values.remediationService.nodeSelector "default" .Values.nodeSelector "indent" 6 "context" . )}}
---
apiVersion: v1
kind: Service
metadata:
  name: remediation-service
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/part-of: keptn-{{ .Release.Namespace }}
    app.kubernetes.io/component: {{ include "control-plane.name" . }}
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector: {{- include "common.labels.selectorLabels" . | nindent 4 }}

