apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "jmeter-service.serviceAccountName" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}


